-- ── Alerts Table ───────────────────────────────────────────────
-- Stores active and historical notifications generated by the system.

CREATE TABLE IF NOT EXISTS alerts (
    alert_id            TEXT        NOT NULL,
    alert_type          TEXT        NOT NULL,   -- 'anomaly' | 'forecast_breach' | 'budget'
    severity            TEXT        NOT NULL,   -- 'low' | 'medium' | 'high' | 'critical'
    
    -- Context
    cloud_provider      TEXT,
    service_category    TEXT,
    account_id          TEXT,
    alert_date          DATE        NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Content
    title               TEXT        NOT NULL,
    message             TEXT        NOT NULL,
    metadata            JSONB,      -- Technical details (ensemble scores, budget thresholds)
    
    -- Status
    is_resolved         BOOLEAN     NOT NULL DEFAULT FALSE,
    resolved_at         TIMESTAMPTZ,
    
    PRIMARY KEY (alert_date, alert_id)
);

-- ── Alert Rules ──────────────────────────────────────────────
-- Defines user-configured thresholds for budget and forecasting alerts.

CREATE TABLE IF NOT EXISTS alert_rules (
    rule_id             SERIAL      PRIMARY KEY,
    name                TEXT        NOT NULL,
    rule_type           TEXT        NOT NULL,   -- 'budget_absolute' | 'forecast_variance'
    cloud_provider      TEXT        NOT NULL,
    service_category    TEXT,
    threshold_value     DOUBLE PRECISION NOT NULL,
    severity            TEXT        NOT NULL,
    is_active           BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Indexes ──────────────────────────────────────────────────
-- Dashboard alert list query
CREATE INDEX IF NOT EXISTS idx_alerts_lookup
    ON alerts (alert_date DESC, severity, is_resolved);

-- Quick unresolved count
CREATE INDEX IF NOT EXISTS idx_alerts_unresolved
    ON alerts (is_resolved) WHERE is_resolved = FALSE;
